# ./config/postgresql.safe.conf
# Base
listen_addresses = '*'
port = 5432
max_connections = 200

# Memory
shared_buffers = 2GB
effective_cache_size = 6GB
work_mem = 16MB
maintenance_work_mem = 1GB

# WAL
wal_level = minimal
synchronous_commit = on
fsync = on
full_page_writes = on
checkpoint_timeout = 15min
checkpoint_completion_target = 0.9
max_wal_size = 16GB
min_wal_size = 2GB
max_wal_senders = 0

# Planner
random_page_cost = 1.1
effective_io_concurrency = 200

# Logging
log_destination = 'stderr'
logging_collector = on
log_min_duration_statement = 2000
log_checkpoints = on
log_connections = off
log_disconnections = off

# Performance tuning
shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.max = 10000
pg_stat_statements.track = all
pg_stat_statements.save = on
track_io_timing = on
